server:
  port: 8089

spring:
  application:
    name: springboot3x-webflux

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 